class RedirectsController < ApplicationController

  def catalog
    case params[:id]
    when '74'
      redirect_to '/catalog/products/sand-ceremonial-suit?variant_id=270'
    when '95'
      redirect_to '/catalog/products/steel-twilight-suit?variant_id=68'
    when '385'
     redirect_to'/catalog/products/the-oahu?variant_id=437'
    when '5775'
     redirect_to'/catalog/products/aries-vest?variant_id=681'
    when '5768'
     redirect_to'/catalog/products'
    when '5760'
     redirect_to'/catalog/products/aries-vest?variant_id=673'
    when '5773'
     redirect_to'/catalog/products/aries-vest?variant_id=679'
    when '5775'
     redirect_to'/catalog/products/aries-vest?variant_id=681'
    when '5762'
     redirect_to'/catalog/products/aries-vest?variant_id=673'
    when '5763'
     redirect_to'/catalog/products/aries-vest?variant_id=675'
    when '5765'
     redirect_to'/catalog/products/aries-vest?variant_id=676'
    when '5766'
     redirect_to'/catalog/products/aries-vest?variant_id=677'
    when '5767'
     redirect_to'/catalog/products/aries-vest?variant_id=678'
    when '5545'
     redirect_to'/catalog/products/faille-vest?variant_id=79'
    when '5546'
     redirect_to'/catalog/products/faille-vest?variant_id=829'
    when '5548'
     redirect_to'/catalog/products/faille-vest?variant_id=830'
    when '5549'
     redirect_to'/catalog/products/faille-vest?variant_id=831'
    when '5550'
     redirect_to'/catalog/products/faille-vest?variant_id=832'
    when '5545'
     redirect_to'/catalog/products/faille-vest?variant_id=833'
    when '5545'
     redirect_to'/catalog/products/faille-vest?variant_id=834'
    when '5545'
     redirect_to'/catalog/products/faille-vest?variant_id=80'
    when '5544'
     redirect_to'/catalog/products/faille-vest?variant_id=77'
    when '5661'
     redirect_to'/catalog/products/lido-vest?variant_id=700'
    when '5662'
     redirect_to'/catalog/products/lido-vest?variant_id=701'
    when '5663'
     redirect_to'/catalog/products/lido-vest?variant_id=702'
    when '5664'
     redirect_to'/catalog/products/lido-vest?variant_id=703'
    when '5666'
     redirect_to'/catalog/products/lido-vest?variant_id=704'
    when '5667'
     redirect_to'/catalog/products/lido-vest?variant_id=705'
    when '5668'
     redirect_to'/catalog/products/lido-vest?variant_id=706'
    when '5673'
     redirect_to'/catalog/products/lido-vest?variant_id=707'
    when '5675'
     redirect_to'/catalog/products/lido-vest?variant_id=708'
    when '5508'
     redirect_to'/catalog/products/mossy-oak-break-up-camo-vest?variant_id=313'
    when '5802'
     redirect_to'/catalog/products/perfect-vest?variant_id=683'
    when '5803'
     redirect_to'/catalog/products/perfect-vest?variant_id=684'
    when '5804'
     redirect_to'/catalog/products/perfect-vest?variant_id=685'
    when '5805'
     redirect_to'/catalog/products/perfect-vest?variant_id=686'
    when '5806'
     redirect_to'/catalog/products/perfect-vest?variant_id=687'
    when '5807'
     redirect_to'/catalog/products/perfect-vest?variant_id=688'
    when '5808'
     redirect_to'/catalog/products/perfect-vest?variant_id=689'
    when '5809'
     redirect_to'/catalog/products/perfect-vest?variant_id=690'
    when '5810'
     redirect_to'/catalog/products/perfect-vest?variant_id=692'
    when '5812'
     redirect_to'/catalog/products/perfect-vest?variant_id=692'
    when '5813'
     redirect_to'/catalog/products/perfect-vest?variant_id=693'
    when '5814'
     redirect_to'/catalog/products/perfect-vest?variant_id=695'
    when '5815'
     redirect_to'/catalog/products/perfect-vest?variant_id=696'
    when '5816'
     redirect_to'/catalog/products/perfect-vest?variant_id=697'
    when '5817'
     redirect_to'/catalog/products/perfect-vest?variant_id=697'
    when '5978'
     redirect_to'/catalog/products/satin-vest?variant_id=519'
    when '5990'
     redirect_to'/catalog/products/satin-vest?variant_id=531'
    when '5980'
     redirect_to'/catalog/products/satin-vest?variant_id=521'
    when '5979'
     redirect_to'/catalog/products/satin-vest?variant_id=520'
    when '5988'
     redirect_to'/catalog/products/satin-vest?variant_id=529'
    when '5981'
     redirect_to'/catalog/products/satin-vest?variant_id=522'
    when '5985'
     redirect_to'/catalog/products/satin-vest?variant_id=526'
    when '5991'
     redirect_to'/catalog/products/satin-vest?variant_id=532'
    when '5984'
     redirect_to'/catalog/products/satin-vest?variant_id=525'
    when '5989'
     redirect_to'/catalog/products/satin-vest?variant_id=530'
    when '5983'
     redirect_to'/catalog/products/satin-vest?variant_id=524'
    when '5987'
     redirect_to'/catalog/products/satin-vest?variant_id=528'
    when '5986'
     redirect_to'/catalog/products/satin-vest?variant_id=527'
    when '5645'
     redirect_to'/catalog/products/spectrum-vest?variant_id=247'
    when '5646'
     redirect_to'/catalog/products/spectrum-vest?variant_id=248'
    when '5647'
     redirect_to'/catalog/products/spectrum-vest?variant_id=249'
    when '5648'
     redirect_to'/catalog/products/spectrum-vest?variant_id=250'
    when '5650'
     redirect_to'/catalog/products/spectrum-vest?variant_id=251'
    when '5651'
     redirect_to'/catalog/products/spectrum-vest?variant_id=252'
    when '5652'
     redirect_to'/catalog/products/spectrum-vest?variant_id=253'
    when '5653'
     redirect_to'/catalog/products/spectrum-vest?variant_id=254'
    when '5654'
     redirect_to'/catalog/products/spectrum-vest?variant_id=255'
    when '5655'
     redirect_to'/catalog/products/spectrum-vest?variant_id=256'
    when '5656'
     redirect_to'/catalog/products/spectrum-vest?variant_id=257'
    when '5657'
     redirect_to'/catalog/products/spectrum-vest?variant_id=260'
    when '5658'
     redirect_to'/catalog/products/spectrum-vest?variant_id=261'
    when '5659'
     redirect_to'/catalog/products/spectrum-vest?variant_id=262'
    when '5524'
     redirect_to'/catalog/products/texas-flag-vest?variant_id=311'
    when '5001'
     redirect_to'/catalog/products/satin-cummerbund?variant_id=74'
    when '5478'
     redirect_to'/catalog/products/satin-cummerbund?variant_id=875'
    when '5479'
     redirect_to'/catalog/products/satin-cummerbund?variant_id=876'
    when '5480'
     redirect_to'/catalog/products/satin-cummerbund?variant_id=877'
    when '5481'
     redirect_to'/catalog/products/satin-cummerbund?variant_id=878'
    when '5482'
     redirect_to'/catalog/products/satin-cummerbund?variant_id=879'
    when '5483'
     redirect_to'/catalog/products/satin-cummerbund?variant_id=880'
    when '5484'
     redirect_to'/catalog/products/satin-cummerbund?variant_id=79'
    when '5485'
     redirect_to'/catalog/products/satin-cummerbund?variant_id=886'
    when '5486'
     redirect_to'/catalog/products/satin-cummerbund?variant_id=219'
    when '5487'
     redirect_to'/catalog/products/satin-cummerbund?variant_id=218'
    when '5488'
     redirect_to'/catalog/products/satin-cummerbund?variant_id=887'
    when '5489'
     redirect_to'/catalog/products/satin-cummerbund?variant_id=888'
    when '5490'
     redirect_to'/catalog/products/satin-cummerbund?variant_id=881'
    when '5491'
     redirect_to'/catalog/products/satin-cummerbund?variant_id=882'
    when '5492'
     redirect_to'/catalog/products/satin-cummerbund?variant_id=883'
    when '5493'
     redirect_to'/catalog/products/satin-cummerbund?variant_id=884'
    when '5494'
     redirect_to'/catalog/products/satin-cummerbund?variant_id=885'
    when '4481'
     redirect_to'/catalog/products/ombre-4-in-hand-tie?variant_id=727'
    when '4260'
     redirect_to'/catalog/products/synergy-4-in-hand-tie?variant_id=588'
    when '4261'
     redirect_to'/catalog/products/synergy-4-in-hand-tie?variant_id=589'
    when '4262'
     redirect_to'/catalog/products/synergy-4-in-hand-tie?variant_id=590'
    when '4263'
     redirect_to'/catalog/products/synergy-4-in-hand-tie?variant_id=591'
    when '4264'
     redirect_to'/catalog/products/synergy-4-in-hand-tie?variant_id=592'
    when '4265'
     redirect_to'/catalog/products/synergy-4-in-hand-tie?variant_id=593'
    when '4266'
     redirect_to'/catalog/products/synergy-4-in-hand-tie?variant_id=594'
    when '4264'
     redirect_to'/catalog/products/synergy-4-in-hand-tie?variant_id=592'
    when '4268'
     redirect_to'/catalog/products/synergy-4-in-hand-tie?variant_id=596'
    when '4269'
     redirect_to'/catalog/products/synergy-4-in-hand-tie?variant_id=597'
    when '4270'
     redirect_to'/catalog/products/synergy-4-in-hand-tie?variant_id=598'
    when '4271'
     redirect_to'/catalog/products/synergy-4-in-hand-tie?variant_id=599'
    when '4272'
     redirect_to'/catalog/products/synergy-4-in-hand-tie?variant_id=600'
    when '4273'
     redirect_to'/catalog/products/synergy-4-in-hand-tie?variant_id=601'
    when '4274'
     redirect_to'/catalog/products/synergy-4-in-hand-tie?variant_id=602'
    when '4275'
     redirect_to'/catalog/products/synergy-4-in-hand-tie?variant_id=603'
    when '4276'
     redirect_to'/catalog/products/synergy-4-in-hand-tie?variant_id=604'
    when '4277'
     redirect_to'/catalog/products/synergy-4-in-hand-tie?variant_id=605'
    when '4278'
     redirect_to'/catalog/products/synergy-4-in-hand-tie?variant_id=606'
    when '4279'
     redirect_to'/catalog/products/synergy-4-in-hand-tie?variant_id=607'
    when '4280'
     redirect_to'/catalog/products/synergy-4-in-hand-tie?variant_id=608'
    when '4281'
     redirect_to'/catalog/products/synergy-4-in-hand-tie?variant_id=609'
    when '4282'
     redirect_to'/catalog/products/synergy-4-in-hand-tie?variant_id=610'
    when '4283'
     redirect_to'/catalog/products/synergy-4-in-hand-tie?variant_id=611'
    when '4645'
     redirect_to'/catalog/products/solid-tie?variant_id=190'
    when '4646'
     redirect_to'/catalog/products/solid-tie?variant_id=191'
    when '4647'
     redirect_to'/catalog/products/solid-tie?variant_id=192'
    when '4648'
     redirect_to'/catalog/products/solid-tie?variant_id=193'
    when '4649'
     redirect_to'/catalog/products/solid-tie?variant_id=194'
    when '4650'
     redirect_to'/catalog/products/solid-tie?variant_id=195'
    when '4651'
     redirect_to'/catalog/products/solid-tie?variant_id=196'
    when '4652'
     redirect_to'/catalog/products/solid-tie?variant_id=197'
    when '4653'
     redirect_to'/catalog/products/solid-tie?variant_id=198'
    when '4654'
     redirect_to'/catalog/products/solid-tie?variant_id=199'
    when '4655'
     redirect_to'/catalog/products/solid-tie?variant_id=200'
    when '4656'
     redirect_to'/catalog/products/solid-tie?variant_id=201'
    when '4657'
     redirect_to'/catalog/products/solid-tie?variant_id=202'
    when '4658'
     redirect_to'/catalog/products/solid-tie?variant_id=203'
    when '4659'
     redirect_to'/catalog/products/solid-tie?variant_id=204'
    when '4660'
     redirect_to'/catalog/products/solid-tie?variant_id=205'
    when '4661'
     redirect_to'/catalog/products/solid-tie?variant_id=206'
    when '4662'
     redirect_to'/catalog/products/solid-tie?variant_id=207'
    when '4663'
     redirect_to'/catalog/products/solid-tie?variant_id=208'
    when '4664'
     redirect_to'/catalog/products/solid-tie?variant_id=209'
    when '4665'
     redirect_to'/catalog/products/solid-tie?variant_id=210'
    when '4666'
     redirect_to'/catalog/products/solid-tie?variant_id=211'
    when '4667'
     redirect_to'/catalog/products/solid-tie?variant_id=212'
    when '4668'
     redirect_to'/catalog/products/solid-tie?variant_id=213'
    when '4669'
     redirect_to'/catalog/products/solid-tie?variant_id=214'
    when '4670'
     redirect_to'/catalog/products/solid-tie?variant_id=215'
    when '4671'
     redirect_to'/catalog/products/solid-tie?variant_id=216'
    when '4673'
     redirect_to'/catalog/products/solid-tie?variant_id=217'
    when '3001'
     redirect_to'/catalog/products/white-pleated-shirt?variant_id=72'
    when '3010'
     redirect_to'/catalog/products/candlelight-micro-fiber-pleated-laydown?variant_id=451'
    when '3011'
     redirect_to'/catalog/products/candlelight-micro-fiber-pleated-wing?variant_id=454'
    when '3025'
     redirect_to'/catalog/products/white-microfiber-slim-fit-shirt?variant_id=456'
    when '3101'
     redirect_to'/catalog/products/white-wing-collar-shirt?variant_id=460'
    when '3215'
     redirect_to'/catalog/products/white-microfiber-wing-shirt?variant_id=221'
    when '3225'
     redirect_to'/catalog/products/white-microfiber-wing-shirt?variant_id=462'
    when '3226'
     redirect_to'/catalog/products/white-microfiber-wing-shirt?variant_id=464'
    when '3228'
     redirect_to'/catalog/products/white-microfiber-wing-shirt?variant_id=466'
    when '7015'
     redirect_to'/catalog/products/black-radio-city?variant_id=84'
    when '7016'
     redirect_to'/catalog/products/black-radio-city?variant_id=550'
    when '7017'
     redirect_to'/catalog/products/black-radio-city?variant_id=551'
    when '7078'
     redirect_to'/catalog/products/stanford?variant_id=553'
    when '7083'
     redirect_to'/catalog/products/cosmo?variant_id=555'
    when '6001'
     redirect_to'/catalog/products/black-on-studs-and-cufflinks?variant_id=82'
    when '6002'
     redirect_to'/catalog/products/black-on-studs-and-cufflinks?variant_id=835'
    when '6101'
     redirect_to'/catalog/products/pearl-on-studs-and-cufflinks?variant_id=848'
    when '6102'
     redirect_to'/catalog/products/pearl-on-studs-and-cufflinks?variant_id=849'
    when '6503'
     redirect_to'/catalog/products/premium-studs-and-cufflinks?variant_id=852' 
    when '385'
     redirect_to'/catalog/products/the-oahu?variant_id=4372'
    when '385'
     redirect_to'/catalog/products/the-oahu?variant_id=4372'
    when '38'
     redirect_to'/catalog/products/2-button-notch?variant_id=176'
    when '5554'
     redirect_to'/catalog/products/faille-vest?variant_id=837'
    when '2'
     redirect_to'/catalog/products/1-button-notch?variant_id=62'
    when '3'
     redirect_to'/catalog/products/classic-full-dress-peak-tails?variant_id=66'
    when '5'
     redirect_to'/catalog/products/the-avalon?variant_id=148'
    when '7'
     redirect_to'/catalog/products/black-couture-peak?variant_id=152'
    when '11'
     redirect_to'/catalog/products/double-breasted-peak?variant_id=163'
    when '12'
     redirect_to'/catalog/products/moet?variant_id=166'
    when '20'
     redirect_to'/catalog/products/republic-2-button-notch?variant_id=170'
    when '30'
     redirect_to'/catalog/products/grey-cutaway?variant_id=172'
    when '45'
     redirect_to'/catalog/products/emerald?variant_id=174'
    when '41'
     redirect_to'/catalog/products/white-shawl-cassic-dinner-jacket?variant_id=178'
    when '43'
     redirect_to'/catalog/products/black-shawl?variant_id=180'
    when '48'
     redirect_to'/catalog/products/el-rey-black?variant_id=182'
    when '49'
     redirect_to'/catalog/products/el-rey-white?variant_id=184'
    when '52'
     redirect_to'/catalog/products/marseille-2-button-peak?variant_id=186'
    when '55'
     redirect_to'/catalog/products/black-cutaway?variant_id=188'
    when '59'
     redirect_to'/catalog/products/oakwood-white?variant_id=243'
    when '61'
     redirect_to'/catalog/products/white-2-button-notch?variant_id=245'
    when '65'
     redirect_to'/catalog/products/cambridge?variant_id=259'
    when '68'
     redirect_to'/catalog/products/white-notch-tails?variant_id=264'
    when '69'
     redirect_to'/catalog/products/oakwood-3-button-notch?variant_id=266'
    when '73'
     redirect_to'/catalog/products/slate-blue-allure?variant_id=268'
    when '76'
     redirect_to'/catalog/products/white-illusion?variant_id=272'
    when '78'
     redirect_to'/catalog/products/parisian-super-100s-chocolate-tone-on-tone-2-button-notch?variant_id=274'
    when '80'
     redirect_to'/catalog/products/midnight-blue-notch?variant_id=276'
    when '81'
     redirect_to'/catalog/products/kors-2-button-notch?variant_id=316'
    when '83'
     redirect_to'/catalog/products/silver-savoy?variant_id=332'
    when '84'
     redirect_to'/catalog/products/ivory-2-button-notch?variant_id=336'
    when '85'
     redirect_to'/catalog/products/the-tex-western-coat-with-satin-yoke?variant_id=362'
    when '202'
     redirect_to'/catalog/products/the-camo-tuxedo?variant_id=366'
    when '203'
     redirect_to'/catalog/products/trail-blazer-tuxedo?variant_id=368'
    when '205'
     redirect_to'/catalog/products/the-zootux?variant_id=370'
    when '207'
     redirect_to'/catalog/products/lone-star-tuxedo?variant_id=372'
    when '255'
     redirect_to'/catalog/products/silverado-tuxedo?variant_id=406'
    when '294'
     redirect_to'/catalog/products/western-tuxedo?variant_id=428'
    when '305'
     redirect_to'/catalog/products/the-gambler?variant_id=430'
    when '411'
     redirect_to'/catalog/products/the-4-1-1?variant_id=442'
    when '10'
     redirect_to'/catalog/products/the-lynx?variant_id=847'
    when '14'
     redirect_to'/catalog/products/black-label-slim-fit-shawl?variant_id=874'
    when '283'
     redirect_to'/catalog/products/the-maverick?variant_id=894'
    when '5992'
     redirect_to'/catalog/products/satin-vest?variant_id=533'
    when '5996'
     redirect_to'/catalog/products/satin-vest?variant_id=537'
    when '5997'
     redirect_to'/catalog/products/satin-vest?variant_id=538'
    when '5860'
     redirect_to'/catalog/products/synergy-vest?variant_id=565'
    when '5861'
     redirect_to'/catalog/products/synergy-vest?variant_id=566'
    when '5862'
     redirect_to'/catalog/products/synergy-vest?variant_id=567'
    when '5863'
     redirect_to'/catalog/products/synergy-vest?variant_id=570'
    when '5865'
     redirect_to'/catalog/products/synergy-vest?variant_id=572'
    when '5866'
     redirect_to'/catalog/products/synergy-vest?variant_id=573'
    when '5867'
     redirect_to'/catalog/products/synergy-vest?variant_id=574'
    when '5868'
     redirect_to'/catalog/products/synergy-vest?variant_id=575'
    when '5869'
     redirect_to'/catalog/products/synergy-vest?variant_id=578'
    when '5870'
     redirect_to'/catalog/products/synergy-vest?variant_id=579'
    when '5871'
     redirect_to'/catalog/products/synergy-vest?variant_id=586'
    when '5874'
     redirect_to'//catalog/products/synergy-vest?variant_id=589'
    when '5875'
     redirect_to'/catalog/products/synergy-vest?variant_id=590'
    when '5877'
     redirect_to'/catalog/products/synergy-vest?variant_id=591'
    when '5878'
     redirect_to'/catalog/products/synergy-vest?variant_id=593'
    when '5880'
     redirect_to'/catalog/products/synergy-vest?variant_id=595'
    when '5881'
     redirect_to'/catalog/products/synergy-vest?variant_id=597'
    when '5882'
     redirect_to'/catalog/products/synergy-vest?variant_id=599'
    when '5883'
     redirect_to'/catalog/products/synergy-vest?variant_id=602'
    when '5883'
     redirect_to'/catalog/products/synergy-vest?variant_id=604'
    when '5885'
     redirect_to'/catalog/products/synergy-vest?variant_id=605'
    when '5886'
     redirect_to'/catalog/products/synergy-vest?variant_id=608'
    when '5887'
     redirect_to'/catalog/products/synergy-vest?variant_id=610'
    when '5888'
     redirect_to'/catalog/products/synergy-vest?variant_id=612'
    when '5889'
     redirect_to'/catalog/products/synergy-vest?variant_id=614'
    when '5890'
     redirect_to'/catalog/products/synergy-vest?variant_id=615'
    when '5891'
     redirect_to'/catalog/products/synergy-vest?variant_id=618'
    when '5685'
     redirect_to'/catalog/products/sienna-vest?variant_id=722'
    when '5686'
     redirect_to'/catalog/products/sienna-vest?variant_id=723'
    when '5687'
     redirect_to'/catalog/products/sienna-vest?variant_id=724'
    when '5689'
     redirect_to'/catalog/products/sienna-vest?variant_id=725'
    when '5691'
     redirect_to'/catalog/products/sienna-vest?variant_id=726'
    when '5693'
     redirect_to'/catalog/products/sienna-vest?variant_id=727'
    when '5695'
     redirect_to'/catalog/products/sienna-vest?variant_id=728'
    when '5710'
     redirect_to'/catalog/products/carino-vest?variant_id=751'
    when '5711'
     redirect_to'/catalog/products/carino-vest?variant_id=752'
    when '5712'
     redirect_to'/catalog/products/carino-vest?variant_id=753'
    when '5713'
     redirect_to'/catalog/products/carino-vest?variant_id=754'
    when '5714'
     redirect_to'/catalog/products/carino-vest?variant_id=755'
    when '5716'
     redirect_to'/catalog/products/carino-vest?variant_id=756'
    when '5717'
     redirect_to'/catalog/products/carino-vest?variant_id=757'
    when '5718'
     redirect_to'/catalog/products/carino-vest?variant_id=758'
    when '5719'
     redirect_to'/catalog/products/carino-vest?variant_id=759'
    when '5720'
     redirect_to'/catalog/products/carino-vest?variant_id=760'
    when '5722'
     redirect_to'/catalog/products/carino-vest?variant_id=761'
    when '5723'
     redirect_to'/catalog/products/carino-vest?variant_id=762'
    when "5724"
     redirect_to '/catalog/products/carino-vest?variant_id=763'
   when "5724"
     redirect_to '/catalog/products/carino-vest?variant_id=763'
    else
      redirect_to"/catalog/products"
    end
  end

  def rentalCategory
    case params[:categoryid]
    when '371'
      redirect_to 'catalog/products?category=vests'
    when '1165'
      redirect_to '/wedding'
    when '375'
      redirect_to '/quinceanera'
    else
      redirect_to '/catalog/products/'
    end
  end

  def misc
    if params[:referrer]
        case params[:referrer]
        when 'utm_source=sidebar'
          redirect_to '/group-offers'
        else
          redirect_to '/'
        end
    elsif (params[:id] && params[:catid])
        redirect_to '/catalog/products'
    elsif params[:id]
        case params[:id]
        when 'referrer=utm_source=sidebar'
          redirect_to '/catalog/products/'
        when '284'
          redirect_to '/catalog/products/duke-tuxedo?variant_id=895'
        when '5994&catid=767'
          redirect_to '/catalog/products/satin-vest?variant_id=535'
        else
          redirect_to '/'
        end
    else 
        redirect_to '/'
    end
  end

  def staticWed
    case params[:id]
    when 'referrer=utm_source=sidebar'
      redirect_to '/wedding'
    else
      redirect_to '/'
    end
  end

end