# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65f2e02471e35cc1ea8918cad73d3b9c738193161de41a03b4169bbe64885440f553c79e8106cc527ad92ebe3d4431027a84c17ba35e74f2a6016ecd5ca97845

test:
  secret_key_base: 8fbe079f795e1682084931482c7d7c1f92eb9aa49d977a004789431fcaefda718ddadf3bdbf70f5707854c970852d339cfd67023855f2ed00c703fd266ffd10a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
